In [49]:
# Statistical Tests and Experiments Notebook
# ------------------------------------------------------------
# This notebook contains runnable Python code for:
# 1. Descriptive statistics
# 2. Sample variance and population variance
# 3. Z-test: one-tailed and two-tailed
# 4. t-test: one-sample, independent, and paired
# 5. Chi-square goodness-of-fit test
# 6. Chi-square test of independence
# 7. F-test for comparing two variances
# 8. One-way ANOVA
# 9. Critical values and decision rules

import numpy as np
import pandas as pd
import scipy.stats as stats

print("Libraries imported successfully.")

Libraries imported successfully.

In [50]:
import numpy as np
import pandas as pd
import scipy.stats as stats

In [51]:
# Helper function for hypothesis test conclusion

def hypothesis_decision(p_value, alpha=0.05):
    """
    If p-value < alpha, reject H0.
    Otherwise, fail to reject H0.
    """
    print(f"Alpha: {alpha}")
    print(f"P-value: {p_value:.6f}")

    if p_value < alpha:
        print("Decision: Reject H0")
        print("Conclusion: Result is statistically significant.")
    else:
        print("Decision: Fail to reject H0")
        print("Conclusion: Result is not statistically significant.")

In [52]:
# 1. Descriptive Statistics
# ------------------------------------------------------------
# Mean, median, mode, variance, standard deviation

data = [70, 72, 68, 71, 75, 74, 73]

mean_value = np.mean(data)
median_value = np.median(data)
sample_variance = np.var(data, ddof=1)
population_variance = np.var(data, ddof=0)
sample_std = np.std(data, ddof=1)

print("Data:", data)
print("Mean:", mean_value)
print("Median:", median_value)
print("Sample Variance:", sample_variance)
print("Population Variance:", population_variance)
print("Sample Standard Deviation:", sample_std)

Data: [70, 72, 68, 71, 75, 74, 73]
Mean: 71.85714285714286
Median: 72.0
Sample Variance: 5.80952380952381
Population Variance: 4.979591836734694
Sample Standard Deviation: 2.410295378065479

In [53]:
# 2. Sample Variance using statistics module
# ------------------------------------------------------------
# stats.variance() gives sample variance.
# stats.pvariance() gives population variance.

import statistics as st

data = [70, 72, 68, 71, 75]

sample_var = st.variance(data)
population_var = st.pvariance(data)

print("Sample variance:", sample_var)
print("Population variance:", population_var)

Sample variance: 6.7
Population variance: 5.36

In [54]:
# 3. One-sample Z-test function
# ------------------------------------------------------------
# Use Z-test when population standard deviation is known.
# alternative = "two-sided", "greater", or "less"

def one_sample_z_test(sample, population_mean, population_std, alternative="two-sided"):
    sample = np.array(sample)
    n = len(sample)
    sample_mean = np.mean(sample)

    z_stat = (sample_mean - population_mean) / (population_std / np.sqrt(n))

    if alternative == "two-sided":
        p_value = 2 * (1 - stats.norm.cdf(abs(z_stat)))
    elif alternative == "greater":
        p_value = 1 - stats.norm.cdf(z_stat)
    elif alternative == "less":
        p_value = stats.norm.cdf(z_stat)
    else:
        raise ValueError("alternative must be 'two-sided', 'greater', or 'less'")

    return z_stat, p_value

print("Z-test function created.")

Z-test function created.

In [55]:
# 4. Two-tailed Z-test example
# ------------------------------------------------------------
# H0: sample mean = population mean
# H1: sample mean != population mean

sample = [52, 55, 53, 56, 54, 57, 58, 55, 56, 54]
population_mean = 50
population_std = 5
alpha = 0.05

z_stat, p_value = one_sample_z_test(
    sample=sample,
    population_mean=population_mean,
    population_std=population_std,
    alternative="two-sided"
)

print("Two-tailed Z-test")
print("Z statistic:", z_stat)
hypothesis_decision(p_value, alpha)

Two-tailed Z-test
Z statistic: 3.1622776601683795
Alpha: 0.05
P-value: 0.001565
Decision: Reject H0
Conclusion: Result is statistically significant.

In [56]:
# 5. Right-tailed Z-test example
# ------------------------------------------------------------
# H0: sample mean <= population mean
# H1: sample mean > population mean

z_stat, p_value = one_sample_z_test(
    sample=sample,
    population_mean=population_mean,
    population_std=population_std,
    alternative="greater"
)

print("Right-tailed Z-test")
print("Z statistic:", z_stat)
hypothesis_decision(p_value, alpha)

Right-tailed Z-test
Z statistic: 3.1622776601683795
Alpha: 0.05
P-value: 0.000783
Decision: Reject H0
Conclusion: Result is statistically significant.

In [57]:
# 6. Left-tailed Z-test example
# ------------------------------------------------------------
# H0: sample mean >= population mean
# H1: sample mean < population mean

z_stat, p_value = one_sample_z_test(
    sample=sample,
    population_mean=population_mean,
    population_std=population_std,
    alternative="less"
)

print("Left-tailed Z-test")
print("Z statistic:", z_stat)
hypothesis_decision(p_value, alpha)

Left-tailed Z-test
Z statistic: 3.1622776601683795
Alpha: 0.05
P-value: 0.999217
Decision: Fail to reject H0
Conclusion: Result is not statistically significant.

In [58]:
# 7. One-sample t-test function
# ------------------------------------------------------------
# Use t-test when population standard deviation is unknown.
# alternative = "two-sided", "greater", or "less"

def one_sample_t_test(sample, population_mean, alternative="two-sided"):
    sample = np.array(sample)
    n = len(sample)
    sample_mean = np.mean(sample)
    sample_std = np.std(sample, ddof=1)
    df = n - 1

    t_stat = (sample_mean - population_mean) / (sample_std / np.sqrt(n))

    if alternative == "two-sided":
        p_value = 2 * (1 - stats.t.cdf(abs(t_stat), df))
    elif alternative == "greater":
        p_value = 1 - stats.t.cdf(t_stat, df)
    elif alternative == "less":
        p_value = stats.t.cdf(t_stat, df)
    else:
        raise ValueError("alternative must be 'two-sided', 'greater', or 'less'")

    return t_stat, p_value, df

print("t-test function created.")

t-test function created.

In [59]:
# 8. Two-tailed one-sample t-test
# ------------------------------------------------------------
# H0: sample mean = population mean
# H1: sample mean != population mean

sample = [52, 55, 53, 56, 54, 57, 58, 55, 56, 54]
population_mean = 50
alpha = 0.05

t_stat, p_value, df = one_sample_t_test(
    sample=sample,
    population_mean=population_mean,
    alternative="two-sided"
)

print("Two-tailed one-sample t-test")
print("t statistic:", t_stat)
print("Degrees of freedom:", df)
hypothesis_decision(p_value, alpha)

Two-tailed one-sample t-test
t statistic: 8.660254037844387
Degrees of freedom: 9
Alpha: 0.05
P-value: 0.000012
Decision: Reject H0
Conclusion: Result is statistically significant.

In [60]:
# 9. Right-tailed one-sample t-test
# ------------------------------------------------------------
# H0: sample mean <= population mean
# H1: sample mean > population mean

t_stat, p_value, df = one_sample_t_test(
    sample=sample,
    population_mean=population_mean,
    alternative="greater"
)

print("Right-tailed one-sample t-test")
print("t statistic:", t_stat)
print("Degrees of freedom:", df)
hypothesis_decision(p_value, alpha)

Right-tailed one-sample t-test
t statistic: 8.660254037844387
Degrees of freedom: 9
Alpha: 0.05
P-value: 0.000006
Decision: Reject H0
Conclusion: Result is statistically significant.

In [61]:
# 10. Left-tailed one-sample t-test
# ------------------------------------------------------------
# H0: sample mean >= population mean
# H1: sample mean < population mean

t_stat, p_value, df = one_sample_t_test(
    sample=sample,
    population_mean=population_mean,
    alternative="less"
)

print("Left-tailed one-sample t-test")
print("t statistic:", t_stat)
print("Degrees of freedom:", df)
hypothesis_decision(p_value, alpha)

Left-tailed one-sample t-test
t statistic: 8.660254037844387
Degrees of freedom: 9
Alpha: 0.05
P-value: 0.999994
Decision: Fail to reject H0
Conclusion: Result is not statistically significant.

In [62]:
# 11. One-sample t-test using SciPy directly
# ------------------------------------------------------------
# SciPy supports alternative="two-sided", "greater", and "less".

sample = [52, 55, 53, 56, 54, 57, 58, 55, 56, 54]
population_mean = 50

print("Two-sided:", stats.ttest_1samp(sample, population_mean, alternative="two-sided"))
print("Greater:", stats.ttest_1samp(sample, population_mean, alternative="greater"))
print("Less:", stats.ttest_1samp(sample, population_mean, alternative="less"))

Two-sided: TtestResult(statistic=np.float64(8.660254037844386), pvalue=np.float64(1.1683873213484005e-05), df=np.int64(9))
Greater: TtestResult(statistic=np.float64(8.660254037844386), pvalue=np.float64(5.8419366067420025e-06), df=np.int64(9))
Less: TtestResult(statistic=np.float64(8.660254037844386), pvalue=np.float64(0.9999941580633933), df=np.int64(9))

In [63]:
# 12. Independent two-sample t-test
# ------------------------------------------------------------
# Use when comparing means of two independent groups.
# Example: marks of Class A and Class B

class_A = [70, 72, 68, 71, 73]
class_B = [80, 82, 85, 83, 81]

# equal_var=True assumes equal variance.
# equal_var=False performs Welch's t-test.
t_stat, p_value = stats.ttest_ind(class_A, class_B, equal_var=True)

print("Independent two-sample t-test")
print("t statistic:", t_stat)
hypothesis_decision(p_value, alpha=0.05)

Independent two-sample t-test
t statistic: -9.37074227640537
Alpha: 0.05
P-value: 0.000014
Decision: Reject H0
Conclusion: Result is statistically significant.

In [64]:
# 13. Paired t-test
# ------------------------------------------------------------
# Use when the same subjects are measured before and after.
# Example: weight before and after diet plan

before = [80, 75, 90, 85, 78]
after = [76, 72, 85, 81, 74]

t_stat, p_value = stats.ttest_rel(before, after)

print("Paired t-test")
print("t statistic:", t_stat)
hypothesis_decision(p_value, alpha=0.05)

Paired t-test
t statistic: 12.649110640673516
Alpha: 0.05
P-value: 0.000225
Decision: Reject H0
Conclusion: Result is statistically significant.

In [65]:
# 14. Chi-square Goodness-of-Fit Test
# ------------------------------------------------------------
# Use when comparing observed counts with expected counts.
# Example: checking whether a dice is fair.

observed = [8, 10, 12, 9, 11, 10]
expected = [10, 10, 10, 10, 10, 10]

chi2_stat, p_value = stats.chisquare(f_obs=observed, f_exp=expected)

print("Chi-square Goodness-of-Fit Test")
print("Chi-square statistic:", chi2_stat)
hypothesis_decision(p_value, alpha=0.05)

Chi-square Goodness-of-Fit Test
Chi-square statistic: 1.0
Alpha: 0.05
P-value: 0.962566
Decision: Fail to reject H0
Conclusion: Result is not statistically significant.

In [66]:
# 15. Chi-square Test of Independence
# ------------------------------------------------------------
# Use when checking relationship between two categorical variables.
# Example: gender and drink preference.

# Rows = Gender: Male, Female
# Columns = Drink preference: Tea, Coffee
table = np.array([
    [40, 60],
    [55, 45]
])

chi2_stat, p_value, dof, expected = stats.chi2_contingency(table)

print("Chi-square Test of Independence")
print("Chi-square statistic:", chi2_stat)
print("Degrees of freedom:", dof)
print("Expected frequencies:")
print(expected)
hypothesis_decision(p_value, alpha=0.05)

Chi-square Test of Independence
Chi-square statistic: 3.9298245614035094
Degrees of freedom: 1
Expected frequencies:
[[47.5 52.5]
 [47.5 52.5]]
Alpha: 0.05
P-value: 0.047437
Decision: Reject H0
Conclusion: Result is statistically significant.

In [67]:
# 16. Chi-square Test of Independence with pandas table
# ------------------------------------------------------------

table_df = pd.DataFrame({
    "Tea": [40, 55],
    "Coffee": [60, 45]
}, index=["Male", "Female"])

print("Observed table:")
display(table_df)

chi2_stat, p_value, dof, expected = stats.chi2_contingency(table_df)

expected_df = pd.DataFrame(
    expected,
    index=table_df.index,
    columns=table_df.columns
)

print("Expected table:")
display(expected_df)

print("Chi-square statistic:", chi2_stat)
print("Degrees of freedom:", dof)
hypothesis_decision(p_value, alpha=0.05)

Observed table:

        Tea  Coffee
Male     40      60
Female   55      45

Expected table:

         Tea  Coffee
Male    47.5    52.5
Female  47.5    52.5

Chi-square statistic: 3.9298245614035094
Degrees of freedom: 1
Alpha: 0.05
P-value: 0.047437
Decision: Reject H0
Conclusion: Result is statistically significant.

In [68]:
# 17. F-test for comparing two variances
# ------------------------------------------------------------
# H0: Variance of group1 = variance of group2
# H1: Variances are different

group1 = [70, 72, 68, 71, 73]
group2 = [80, 85, 78, 90, 88]
alpha = 0.05

var1 = np.var(group1, ddof=1)
var2 = np.var(group2, ddof=1)

# Put larger variance in numerator for two-tailed F-test
if var1 >= var2:
    F_stat = var1 / var2
    df1 = len(group1) - 1
    df2 = len(group2) - 1
else:
    F_stat = var2 / var1
    df1 = len(group2) - 1
    df2 = len(group1) - 1

p_value = 2 * (1 - stats.f.cdf(F_stat, df1, df2))

print("F-test for two variances")
print("Variance group1:", var1)
print("Variance group2:", var2)
print("F statistic:", F_stat)
print("df1:", df1)
print("df2:", df2)
hypothesis_decision(p_value, alpha)

F-test for two variances
Variance group1: 3.6999999999999997
Variance group2: 26.2
F statistic: 7.081081081081082
df1: 4
df2: 4
Alpha: 0.05
P-value: 0.084298
Decision: Fail to reject H0
Conclusion: Result is not statistically significant.

In [69]:
# 18. F critical value
# ------------------------------------------------------------
# F_critical = F inverse CDF at 1 - alpha
# In SciPy: stats.f.ppf(q=1-alpha, dfn=df1, dfd=df2)

alpha = 0.05
df1 = 2
df2 = 9

F_critical = stats.f.ppf(q=1-alpha, dfn=df1, dfd=df2)

print("F critical value:", F_critical)

F critical value: 4.256494729093747

In [70]:
# 19. One-way ANOVA
# ------------------------------------------------------------
# Use when comparing means of 3 or more independent groups.
# Example: three teaching methods.

method_A = [70, 72, 68, 71]
method_B = [80, 82, 85, 83]
method_C = [75, 78, 74, 76]

F_stat, p_value = stats.f_oneway(method_A, method_B, method_C)

print("One-way ANOVA")
print("F statistic:", F_stat)
hypothesis_decision(p_value, alpha=0.05)

One-way ANOVA
F statistic: 44.43442622950811
Alpha: 0.05
P-value: 0.000022
Decision: Reject H0
Conclusion: Result is statistically significant.

In [71]:
# 20. Manual One-way ANOVA calculation
# ------------------------------------------------------------
# This shows how ANOVA gets F = MS_between / MS_within.

groups = [method_A, method_B, method_C]
k = len(groups)
N = sum(len(g) for g in groups)

group_means = [np.mean(g) for g in groups]
grand_mean = np.mean([x for g in groups for x in g])

SS_between = sum(len(g) * (np.mean(g) - grand_mean)**2 for g in groups)
SS_within = sum(sum((x - np.mean(g))**2 for x in g) for g in groups)
SS_total = SS_between + SS_within

df_between = k - 1
df_within = N - k

MS_between = SS_between / df_between
MS_within = SS_within / df_within

F_stat_manual = MS_between / MS_within
p_value_manual = 1 - stats.f.cdf(F_stat_manual, df_between, df_within)

anova_table = pd.DataFrame({
    "Source": ["Between Groups", "Within Groups", "Total"],
    "SS": [SS_between, SS_within, SS_total],
    "df": [df_between, df_within, N - 1],
    "MS": [MS_between, MS_within, np.nan],
    "F": [F_stat_manual, np.nan, np.nan],
    "p-value": [p_value_manual, np.nan, np.nan]
})

display(anova_table)
hypothesis_decision(p_value_manual, alpha=0.05)

           Source          SS  df          MS          F   p-value
0  Between Groups  301.166667   2  150.583333  44.434426  0.000022
1   Within Groups   30.500000   9    3.388889        NaN       NaN
2           Total  331.666667  11         NaN        NaN       NaN

Alpha: 0.05
P-value: 0.000022
Decision: Reject H0
Conclusion: Result is statistically significant.

In [72]:
# 21. Significance and p-value rule
# ------------------------------------------------------------
# alpha = 0.05 means 5% significance level.
# If p-value < alpha, reject H0.
# If p-value >= alpha, fail to reject H0.

alpha = 0.05
example_p_values = [0.01, 0.03, 0.05, 0.10, 0.20]

for p in example_p_values:
    print("-" * 40)
    print("P-value:", p)
    hypothesis_decision(p, alpha)

----------------------------------------
P-value: 0.01
Alpha: 0.05
P-value: 0.010000
Decision: Reject H0
Conclusion: Result is statistically significant.
----------------------------------------
P-value: 0.03
Alpha: 0.05
P-value: 0.030000
Decision: Reject H0
Conclusion: Result is statistically significant.
----------------------------------------
P-value: 0.05
Alpha: 0.05
P-value: 0.050000
Decision: Fail to reject H0
Conclusion: Result is not statistically significant.
----------------------------------------
P-value: 0.1
Alpha: 0.05
P-value: 0.100000
Decision: Fail to reject H0
Conclusion: Result is not statistically significant.
----------------------------------------
P-value: 0.2
Alpha: 0.05
P-value: 0.200000
Decision: Fail to reject H0
Conclusion: Result is not statistically significant.